#!/usr/bin/env python3
"""
Regenerate _redirects with explicit 301! rules for every opinion-*, explainer-*,
and author-* page so extensionless URLs always redirect to the canonical .html form.

Run manually: python update_redirects.py
Also called automatically by update_articles.yml before each CI commit.

Background: Netlify serves both /slug and /slug.html as 200 regardless of the
pretty_urls = false setting in netlify.toml (that setting only affects processing,
not serving). Non-force 301 redirect rules are silently ignored when Netlify finds
a matching file, and wildcard force-redirects (/opinion-*) can't exclude .html
suffixes — so /slug.html would redirect to /slug.html.html (404). The only
reliable fix is an explicit 301! rule per slug, regenerated on every publish run.
"""
import glob
import os
import re

CANONICAL_ALIASES = {
    "author-khalid-kayo": "/author-kalid-kayo.html",
}

STATIC_RETIRED = {
    "djibouti.html", "eritrea.html", "ethiopia.html", "kenya.html",
    "somalia.html", "south-sudan.html", "sudan.html",
}

STATIC_HEADER = """\
# ── Force non-www to canonical https ──────────────────────────
http://hornupdates.com/*   https://hornupdates.com/:splat  301!
http://www.hornupdates.com/*  https://hornupdates.com/:splat  301!
https://www.hornupdates.com/*  https://hornupdates.com/:splat  301!

# ── index.html → / ────────────────────────────────────────────
/index.html  /  301!

# ── Static pages ──────────────────────────────────────────────
/about                /about.html            301!
/contact              /contact.html          301!
/disclaimer           /disclaimer.html       301!
/editorial-policy     /editorial-policy.html 301!
/explainers           /explainers.html       301!
/opinion              /opinion.html          301!
/privacy              /privacy.html          301!
/signal-brief         /signal-brief.html     301!
/terms                /terms.html            301!
/author-khalid-kayo   /author-kalid-kayo.html 301!
/author-khalid-kayo.html /author-kalid-kayo.html 301!

# ── Retired indexes and feed alias ───────────────────────────
/djibouti.html        /                       410!
/eritrea.html         /                       410!
/ethiopia.html        /                       410!
/kenya.html           /                       410!
/somalia.html         /                       410!
/south-sudan.html     /                       410!
/sudan.html           /                       410!
/rss.xml              /feed.xml               301!
"""

SECTION_NOTE = """\
# ── Per-article extensionless → .html redirects ──────────────
# Auto-generated by update_redirects.py — do not edit this section manually.
# Netlify serves /slug and /slug.html both as 200 (pretty_urls=false has no
# effect on actual file serving). Explicit rules are the only reliable fix.
# This file is regenerated on every CI publish run so new articles are always
# covered automatically.
"""


def rules_for(pattern, label):
    files = sorted(glob.glob(pattern))
    if not files:
        return ""
    lines = [f"# {label}"]
    for f in files:
        slug = os.path.basename(f).removesuffix(".html")
        fname = os.path.basename(f)
        destination = CANONICAL_ALIASES.get(slug, f"/{fname}")
        lines.append(f"/{slug:<82}{destination}  301!")
    return "\n".join(lines)


def main():
    existing = ""
    if os.path.exists("_redirects"):
        with open("_redirects", encoding="utf-8") as f:
            existing = f.read()

    retired = []
    for line in existing.splitlines():
        match = re.match(r"^/([^ ]+\.html)\s+.*\s410!$", line.strip())
        if not match:
            continue
        if os.path.exists(match.group(1)):
            continue
        if match.group(1).removesuffix(".html") in CANONICAL_ALIASES:
            continue
        if match.group(1) in STATIC_RETIRED:
            continue
        if line.strip() not in retired:
            retired.append(line.strip())

    opinions = rules_for("opinion-*.html", "Opinion articles")
    explainers = rules_for("explainer-*.html", "Explainers")
    authors = rules_for("author-*.html", "Author pages")

    sections = [STATIC_HEADER, SECTION_NOTE]
    for block in (opinions, explainers, authors):
        if block:
            sections.append(block)
    if retired:
        sections.append("# Retired pages — preserve 410 responses for search engines\n" + "\n".join(sorted(retired)))

    content = "\n".join(sections) + "\n"

    with open("_redirects", "w", encoding="utf-8") as f:
        f.write(content)

    total = sum(1 for b in (opinions, explainers, authors)
                if b for line in b.split("\n") if line.startswith("/"))
    print(f"_redirects updated — {total} per-article redirect rules written.")


if __name__ == "__main__":
    main()
